name: Clear Ephemeral Environments

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  list:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::814320462898:role/iac
          aws-region: us-east-1

      - run: |
          KEYS=$(aws s3api list-objects --bucket santunioni-iac-state --prefix env:/ --output json --query 'Contents[*].Key' | jq '[.[] | select(. | test("realworld-app\/\\w+.tfstate$"))]')
          TERRAFORM_WORKSPACES=$(echo $KEYS | jq '[.[] | sub("^env:\/";"") | sub("\/realworld-app\/\\w+.tfstate$";"")]')
          echo "ENVIRONMENTS=$(echo $TERRAFORM_WORKSPACES | jq -r tostring)" >> $GITHUB_OUTPUT
        shell: bash
        id: list
    outputs:
      environments: ${{ steps.list.outputs.ENVIRONMENTS }}

  clear:
    needs: list
    strategy:
      matrix:
        environment: ${{ fromJson(needs.list.outputs.environments) }}
    uses: ./.github/workflows/clear.yaml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
